name: Publish
on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS CLI
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region eu-north-1

      - uses: actions/checkout@v4
      - uses: pnpm action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run build

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Deploy to S3
        run: |
          aws s3 sync ./build/ s3://portfolio-grindhead --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}